// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIwawixnN6It6KhwRldEEFV-ZjdckOvqU',
    appId: '1:1092183100316:web:651e4530aa9e8283c9d659',
    messagingSenderId: '1092183100316',
    projectId: 'healt-4312',
    authDomain: 'healt-4312.firebaseapp.com',
    storageBucket: 'healt-4312.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4guo71-QT-7VLcEBXrlL-Cklw5PPEn-g',
    appId: '1:1092183100316:android:569e65955264e58fc9d659',
    messagingSenderId: '1092183100316',
    projectId: 'healt-4312',
    storageBucket: 'healt-4312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKBdsIBkELi9pxPSzL-ZAe_bPY1cIt4OM',
    appId: '1:1092183100316:ios:9a0e0e4269250b17c9d659',
    messagingSenderId: '1092183100316',
    projectId: 'healt-4312',
    storageBucket: 'healt-4312.firebasestorage.app',
    iosBundleId: 'com.example.pharmacy',
  );

}